#!/bin/sh -e

cargo build \
    --release \
    --locked

install -Dm755 target/release/kkfetch "$1/usr/bin/kkfetch"
install -Dm644 completions/kkfetch.bash "$1/usr/share/bash-completion/completions/kkfetch"
install -Dm644 completions/_kkfetch "$1/usr/share/zsh/site-functions/_kkfetch"
install -Dm644 completions/kkfetch.fish "$1/usr/share/fish/vendor_completions.d/kkfetch.fish"
install -Dm644 README.md "$1/usr/share/doc/kkfetch/README.md"
install -Dm644 LICENSE "$1/usr/share/licenses/kkfetch/LICENSE"
